### ISSUE TITLE
Deletion of user-owned entities fails

### ISSUE THREAD

**Issue by ToxSox** [Eagle3386/aya-platform#15] opened 2019-05-13 10:33 UTC
**Describe the bug**
A normal user (no judge or admin) get an error on delete his car. The error message is: "Fehler: Fahrzeug nicht gelöscht (unbekannter Fehler). Bitte korrigieren!" and on firefox console i get "Only administrators/jurors beyond this point! Sorry."

**To Reproduce**
1. Go to 'USERNAME'
2. Click on 'FAHRZEUGE'
3. Click on 'LÖSCHEN'

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Browser: firefox
 - Version 67

**Comment by Eagle3386** [comment] 2019-05-13 11:03
Confirmed, happens due to missing check for case "user deletes his own stuff" here: https://github.com/Eagle3386/aya-platform/blob/240e4f778a7fb551668ed0eeddf9d25dc8fdf26c/events/ajax/delete-entities.php#L18

Will be fixed later today.

**Comment by Eagle3386** [comment] 2019-05-21 19:38
Sorry for the delay, been busy all day at work. Latest fix enables users to delete their attendances & vehicles on their own.

**Closed by Eagle3386** 2019-05-21 19:38 UTC
Labels: bug
